# Generated by Django 4.1.7 on 2023-02-19 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notapaciente',
            name='propietario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='paciente.paciente'),
        ),
    ]
