# Generated by Django 4.1.7 on 2023-02-17 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotopaciente/%Y/%m/%d'),
        ),
        migrations.CreateModel(
            name='Preferencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_pareja', models.CharField(blank=True, max_length=25, null=True)),
                ('fecha_aniversario', models.DateField(blank=True, null=True)),
                ('nombre_hijos', models.CharField(blank=True, max_length=25, null=True)),
                ('fecha_hijo', models.DateField(blank=True, null=True)),
                ('nombre_empresa', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_empresa', models.DateField(blank=True, null=True)),
                ('deportes', models.CharField(blank=True, max_length=150, null=True)),
                ('pelicula_serie', models.CharField(blank=True, max_length=150, null=True)),
                ('musica', models.CharField(blank=True, max_length=150, null=True)),
                ('vehiculo', models.CharField(blank=True, max_length=150, null=True)),
                ('comida', models.CharField(blank=True, max_length=150, null=True)),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paciente.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='NotaPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alergias', models.CharField(blank=True, max_length=250, null=True)),
                ('expectativas', models.CharField(blank=True, max_length=250, null=True)),
                ('pade_actual', models.CharField(blank=True, max_length=250, null=True)),
                ('observaciones', models.CharField(blank=True, max_length=250, null=True)),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paciente.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='DatosGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, max_length=10, null=True)),
                ('celular', models.CharField(blank=True, max_length=10, null=True)),
                ('domicilio', models.CharField(blank=True, max_length=150, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=150, null=True)),
                ('estado', models.CharField(blank=True, max_length=150, null=True)),
                ('cp', models.PositiveIntegerField(blank=True, max_length=5, null=True)),
                ('lugar_nacimiento', models.CharField(blank=True, max_length=150, null=True)),
                ('ocupacion', models.CharField(blank=True, max_length=50, null=True)),
                ('region', models.CharField(blank=True, max_length=50, null=True)),
                ('clave_app', models.CharField(blank=True, max_length=10, null=True)),
                ('datofiscal', models.FileField(blank=True, null=True, upload_to='datofiscal/%Y/%m/%d', verbose_name='Curriculum vitae')),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paciente.paciente')),
            ],
        ),
    ]
