# Generated by Django 4.1.7 on 2023-02-17 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0002_paciente_foto_preferencias_notapaciente_datosgeneral'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosgeneral',
            name='cp',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
