# Generated by Django 4.1.7 on 2023-02-19 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0002_alter_notapaciente_propietario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antecedentealimenticio',
            name='propietario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='paciente.paciente'),
        ),
        migrations.AlterField(
            model_name='antecedentefamiliar',
            name='propietario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='paciente.paciente'),
        ),
        migrations.AlterField(
            model_name='antecedentepatologico',
            name='propietario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='paciente.paciente'),
        ),
        migrations.AlterField(
            model_name='datosgeneral',
            name='propietario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='paciente.paciente'),
        ),
        migrations.AlterField(
            model_name='exploracion',
            name='propietario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='paciente.paciente'),
        ),
        migrations.AlterField(
            model_name='preferencia',
            name='propietario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='paciente.paciente'),
        ),
    ]
