# Generated by Django 4.1.7 on 2023-02-27 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0004_alter_paciente_apellido_alter_paciente_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preferencia',
            name='puesti',
        ),
        migrations.AddField(
            model_name='preferencia',
            name='experiencia',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='preferencia',
            name='puesto',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='preferencia',
            name='comida',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='preferencia',
            name='deportes',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='preferencia',
            name='fecha_aniversario',
            field=models.DateField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='preferencia',
            name='fecha_empresa',
            field=models.DateField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='preferencia',
            name='fecha_hijo',
            field=models.DateField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='preferencia',
            name='musica',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='preferencia',
            name='nombre_empresa',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='preferencia',
            name='nombre_hijos',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='preferencia',
            name='nombre_pareja',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='preferencia',
            name='pelicula_serie',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='preferencia',
            name='vehiculo',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name=''),
        ),
    ]
