# Generated by Django 4.1.7 on 2023-02-27 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0005_remove_preferencia_puesti_preferencia_experiencia_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preferencia',
            old_name='puesto',
            new_name='gustos',
        ),
    ]
