# Generated by Django 4.1.7 on 2023-03-04 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0006_rename_puesto_preferencia_gustos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antecedentepersonal',
            name='ultima_desparacita',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
