# Generated by Django 4.1.7 on 2023-03-04 06:04

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0007_alter_antecedentepersonal_ultima_desparacita'),
    ]

    operations = [
        migrations.AddField(
            model_name='antecedentealimenticio',
            name='my_field2',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Item title 2.1'), (2, 'Item title 2.2'), (3, 'Item title 2.3'), (4, 'Item title 2.4'), (5, 'Item title 2.5')], default=1, max_length=3),
            preserve_default=False,
        ),
    ]
