# Generated by Django 4.1.7 on 2023-03-04 06:15

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0008_antecedentealimenticio_my_field2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='antecedentealimenticio',
            name='my_field2',
        ),
        migrations.AlterField(
            model_name='antecedentealimenticio',
            name='comidas',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'Desayuno'), (2, 'Desayuno'), (3, 'Almuerzo'), (4, 'Comida'), (5, 'Colaciones')], max_length=5, null=True),
        ),
    ]
