# Generated by Django 4.1.7 on 2023-03-20 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0009_remove_antecedentealimenticio_my_field2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='antecedentealimenticio',
            name='comidas',
        ),
        migrations.AddField(
            model_name='antecedentealimenticio',
            name='almuerzo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='antecedentealimenticio',
            name='cena',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='antecedentealimenticio',
            name='colaciones',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='antecedentealimenticio',
            name='comida',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='antecedentealimenticio',
            name='desayuno',
            field=models.BooleanField(default=False),
        ),
    ]
