# Generated by Django 4.1.7 on 2023-03-20 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0011_alter_paciente_tipo_sexo_delete_tiposexo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoSexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=8, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='tiposangre',
            name='nombre',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='tipousuario',
            name='nombre',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='tipo_sexo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='paciente.tiposexo', verbose_name='Tipo de sexo'),
        ),
    ]
